
version: '3.8'
networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net  


  web-blue-01:
    image: cesarags/web-color:blue
    container_name: web-color-blue01
    networks:
        - nginx_net  

  web-blue-02:
    image: cesarags/web-color:blue
    container_name: web-color-blue02
    networks:
        - nginx_net 
      
  web-green-01:
    image: cesarags/web-color:green
    container_name: web-color-green01
    networks:
        - nginx_net 
      
  web-green-02:
    image: cesarags/web-color:green
    container_name: web-color-green02
    networks:
        - nginx_net 